spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security_db
    username: postgres
    password: watermelon
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.yandex.ru
    username: iashcherbakov@edu.hse.ru
    password: sydqclwevegqekmr
    port: 465
    protocol: smtps

upload:
  path: /Users/yurishcherbakov/Desktop/uploads
